import glob
import os

from gates.gate_runner import GateCheck
from profiles.base import SpecProfile, run_shell
from utils.design_tokens import load_config, theme_lines, generated_block

DESIGN_PATH = "sdlc/ui-design/DESIGN.md"
STITCH_DIR_DEFAULT = "sdlc/ui-design/stitch"
TOKENS_SCRIPT = ".scripts/utils/design_tokens.py"

# Common global-stylesheet locations, most specific frameworks first. Used
# when profiles."stitch-ui".css_path is not configured.
CSS_CANDIDATES = [
    "src/app/globals.css",
    "app/globals.css",
    "src/styles/globals.css",
    "styles/globals.css",
    "src/index.css",
    "src/globals.css",
]


class StitchUiProfile(SpecProfile):
    """UI design captured as Stitch screen exports; verified by checking the
    application's global stylesheet against the design tokens embedded in
    those exports.

    Unlike the other profiles, the spec artifacts (DESIGN.md plus
    ``code.html`` screen exports under ``sdlc/ui-design/stitch/``) are
    produced by the ui-design stage — retrieved via the Stitch MCP connection
    by the skill, or exported manually from Stitch — not generated by the
    requirements stage. The requirements gate only asserts they were
    captured; the coding stage deterministically ports the tokens into the
    global stylesheet before checking; the testing stage re-checks the final
    state so a hand-edit that drops tokens fails the gate.
    """

    name = "stitch-ui"
    display_name = "Stitch UI Design"

    def stitch_dir(self) -> str:
        return self.profile_config.stitch_dir or STITCH_DIR_DEFAULT

    def css_path(self) -> str:
        if self.profile_config.css_path:
            return self.profile_config.css_path
        for candidate in CSS_CANDIDATES:
            if os.path.exists(os.path.join(self.project_root, candidate)):
                return candidate
        return CSS_CANDIDATES[0]

    def _screen_exports(self) -> list[str]:
        return sorted(glob.glob(
            os.path.join(self.stitch_dir(), "**", "code.html"), recursive=True))

    # --- requirements stage ----------------------------------------------

    def spec_prompt_fragment(self) -> str:
        return (
            "### Stitch UI design conformance\n"
            f"The UI design is specified by {DESIGN_PATH} and the Stitch screen "
            f"exports under {self.stitch_dir()}/ (provided as input documents). "
            "In ## Acceptance Criteria, include one criterion per screen stating "
            "that the implemented screen matches its Stitch export (layout, "
            "components, and design tokens), with Verified By set to "
            f"`{TOKENS_SCRIPT} check`.\n"
        )

    def parse_and_write(self, llm_content: str) -> list[str]:
        # Spec artifacts come from the ui-design stage, not the LLM output.
        return []

    def spec_artifacts(self) -> list[str]:
        artifacts = [DESIGN_PATH] if os.path.exists(DESIGN_PATH) else []
        return artifacts + self._screen_exports()

    def requirements_gate_checks(self) -> list[GateCheck]:
        def _check() -> tuple[bool, str]:
            if not os.path.exists(DESIGN_PATH):
                return False, f"{DESIGN_PATH} does not exist — run /ui-design first"
            exports = self._screen_exports()
            if not exports:
                return False, (
                    f"No Stitch screen exports (code.html) found under "
                    f"{self.stitch_dir()}/ — retrieve them via the Stitch MCP "
                    f"connection during /ui-design, or export each screen's "
                    f"code.html from Stitch into that directory"
                )
            try:
                theme, _ = load_config(self.stitch_dir())
            except SystemExit as e:
                return False, str(e)
            tokens = theme_lines(theme)
            if not tokens:
                return False, (
                    f"Stitch exports under {self.stitch_dir()}/ carry no "
                    f"extractable tailwind.config design tokens"
                )
            return True, (
                f"{len(exports)} Stitch screen export(s) with "
                f"{len(tokens)} design token(s) captured"
            )
        return [GateCheck("stitch_exports_captured",
                          "Stitch screen exports captured with design tokens", _check)]

    def cleanup_artifacts(self):
        # The exports belong to the ui-design stage; a failed requirements
        # run must not delete them.
        pass

    # --- coding stage ------------------------------------------------------

    def coding_context(self) -> str:
        parts = []
        if os.path.exists(DESIGN_PATH):
            with open(DESIGN_PATH) as f:
                parts.append(f"--- {DESIGN_PATH} ---\n{f.read()}")
        exports = self._screen_exports()
        if exports:
            try:
                theme, material = load_config(self.stitch_dir())
            except SystemExit:
                theme, material = {}, False
            if theme:
                parts.append(
                    f"Stitch design tokens — the global stylesheet "
                    f"{self.css_path()} MUST contain this generated block "
                    f"(it is ported mechanically by {TOKENS_SCRIPT}, so include "
                    f"it verbatim):\n{generated_block(theme, material)}"
                )
            parts.append(
                "Stitch screen exports (reference markup for layout and the "
                "custom token utility classes to reuse):\n- " + "\n- ".join(exports)
            )
        if not parts:
            return ""
        return "Stitch UI design spec:\n" + "\n\n".join(parts)

    def coding_scaffold_targets(self, arch_targets: list[str]) -> list[str]:
        # The global stylesheet is a first-class target: token verification
        # runs against it, so it must exist even if ARCH.md omitted it.
        return [self.css_path()] if self._screen_exports() else []

    def coding_prompt_fragment(self) -> str:
        return (
            f"UI code must reproduce the Stitch screen exports: reuse their "
            f"custom Tailwind token utility classes (e.g. p-lg, "
            f"text-headline-sm, bg-surface-container-lowest) rather than "
            f"ad-hoc values, and {self.css_path()} must declare every token "
            f"in a @theme block (the exact block is provided in the context). "
            f"Conformance is verified with `{self.resolve_command()}`."
        )

    # --- verification -------------------------------------------------------

    def resolve_command(self) -> str:
        if self.profile_config.command:
            return self.profile_config.command
        return (f"python3 {TOKENS_SCRIPT} check {self.stitch_dir()} "
                f"--css {self.css_path()}")

    def preflight(self) -> tuple[bool, str]:
        exports = self._screen_exports()
        if not exports:
            return False, (
                f"No Stitch screen exports (code.html) under {self.stitch_dir()}/. "
                f"Retrieve them via the Stitch MCP connection during /ui-design "
                f"(or export them manually from Stitch), or remove stitch-ui "
                f"from the selected spec profiles."
            )
        return True, f"{len(exports)} Stitch screen export(s) found"

    def coding_verification_gate_checks(self, detail_chars: int = 2000) -> list[GateCheck]:
        """In the coding loop, run the mechanical token port before checking.
        The port is idempotent and confined to a marker-delimited block, so
        this deterministically closes the partial-token-port failure mode
        instead of asking the LLM to transcribe tokens correctly."""
        def _port() -> tuple[bool, str]:
            if self.profile_config.command:
                return True, "Custom verifier configured — token port skipped"
            command = (f"python3 {TOKENS_SCRIPT} port {self.stitch_dir()} "
                       f"--css {self.css_path()}")
            result = run_shell(command, self.config.timeouts.command_seconds)
            if result["exit_code"] != 0:
                tail = result["output"][-detail_chars:] if result["output"] else "(no output)"
                return False, f"Token port failed: {command}\n{tail}"
            return True, f"Design tokens ported: {command}"
        return [GateCheck("stitch_tokens_ported", "Stitch design tokens ported", _port)] \
            + self.verification_gate_checks(detail_chars)
