"""Deterministic Stitch → Tailwind v4 design-token port.

Stitch screen exports (``UI_design/<screen>/code.html``) carry an inline
``tailwind.config = {...}`` defining the design system's custom tokens
(colors, spacing scale, typography scale, radii). Application code generated
from those exports reuses the custom class names (``p-lg``,
``text-headline-sm``, ``bg-surface-container-lowest``), but Tailwind v4
silently ignores any utility whose token is not declared in ``@theme`` — a
partial hand-port produces a page with collapsed spacing and default type
with no build error. This module makes the port mechanical instead.

Usage:
    python3 .scripts/utils/design_tokens.py validate <code.html|UI_design_dir>
    python3 .scripts/utils/design_tokens.py port  <code.html|UI_design_dir> --css <globals.css>
    python3 .scripts/utils/design_tokens.py check <code.html|UI_design_dir> --css <globals.css>

``validate`` exits non-zero unless the source contains at least one screen
export with an extractable, non-empty token set — the ui-design stage gate,
runnable before any application stylesheet exists. ``port`` writes (or
refreshes) a marker-delimited generated block in the CSS file containing the
full ``@theme`` plus Material Symbols icon CSS when the export loads that
font. ``check`` exits non-zero listing every expected token missing from the
CSS file, so it can run as a deterministic gate.

When given a directory, every ``code.html`` beneath it is merged (later
screens override earlier ones on key collisions).
"""

import argparse
import glob
import json
import os
import re
import sys

MARKER_START = "/* sdlc:design-tokens:start — generated by .scripts/utils/design_tokens.py; do not edit by hand */"
MARKER_END = "/* sdlc:design-tokens:end */"

MATERIAL_SYMBOLS_CSS = """.material-symbols-outlined {
  font-family: "Material Symbols Outlined";
  font-weight: normal;
  font-style: normal;
  font-variation-settings: "FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24;
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
}"""

# fontSize option keys → Tailwind v4 @theme companion-variable suffixes.
FONT_SIZE_OPTION_SUFFIXES = {
    "lineHeight": "--line-height",
    "letterSpacing": "--letter-spacing",
    "fontWeight": "--font-weight",
}

UNQUOTED_KEY_RE = re.compile(r'([{,]\s*)([A-Za-z_$][A-Za-z0-9_$-]*)\s*:')


def extract_tailwind_config(html: str) -> dict:
    """Pull the inline ``tailwind.config = {...}`` object out of a Stitch
    export and parse it. Returns {} when the export carries no config."""
    anchor = html.find("tailwind.config")
    if anchor == -1:
        return {}
    start = html.find("{", anchor)
    if start == -1:
        return {}

    depth = 0
    in_string = None
    end = None
    i = start
    while i < len(html):
        ch = html[i]
        if in_string:
            if ch == "\\":
                i += 2
                continue
            if ch == in_string:
                in_string = None
        elif ch in "\"'":
            in_string = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
        i += 1
    if end is None:
        return {}

    js_object = html[start:end]
    # The config is a JS object literal, not JSON: keys are unquoted.
    as_json = UNQUOTED_KEY_RE.sub(r'\1"\2":', js_object)
    try:
        return json.loads(as_json)
    except json.JSONDecodeError as e:
        raise SystemExit(f"error: could not parse tailwind.config as JSON after key-quoting: {e}")


def _deep_merge(base: dict, overlay: dict) -> dict:
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value
    return base


def load_config(path: str) -> tuple[dict, bool]:
    """Load and merge tailwind configs from a code.html file or a directory
    of screen exports. Returns (merged_theme_dict, uses_material_symbols)."""
    if os.path.isdir(path):
        files = sorted(glob.glob(os.path.join(path, "**", "code.html"), recursive=True))
    else:
        files = [path]
    if not files:
        raise SystemExit(f"error: no code.html found under {path}")

    merged: dict = {}
    material = False
    for f in files:
        with open(f) as fh:
            html = fh.read()
        config = extract_tailwind_config(html)
        theme = (config.get("theme") or {})
        # Tokens may sit under theme.extend or directly under theme.
        _deep_merge(merged, theme.get("extend") or {})
        _deep_merge(merged, {k: v for k, v in theme.items() if k != "extend"})
        if "Material Symbols" in html or "Material+Symbols" in html:
            material = True
    return merged, material


def _font_value(families) -> str:
    if isinstance(families, str):
        families = [families]
    quoted = [f'"{f}"' for f in families]
    generic = "monospace" if any("mono" in f.lower() for f in families) else "sans-serif"
    return ", ".join(quoted + [generic])


def theme_lines(theme: dict) -> list[str]:
    """Flatten a parsed tailwind theme dict into Tailwind v4 @theme
    declarations, ordered by namespace for stable output."""
    lines = []

    for name, value in sorted((theme.get("colors") or {}).items()):
        if isinstance(value, dict):
            for shade, shade_value in sorted(value.items()):
                lines.append(f"  --color-{name}-{shade}: {shade_value};")
        else:
            lines.append(f"  --color-{name}: {value};")

    for name, value in sorted((theme.get("spacing") or {}).items()):
        lines.append(f"  --spacing-{name}: {value};")

    for name, value in sorted((theme.get("borderRadius") or {}).items()):
        if name == "DEFAULT":
            # Tailwind v4 has no bare --radius variable; the bare `rounded`
            # utility keeps its built-in 0.25rem, which matches Stitch output.
            continue
        lines.append(f"  --radius-{name}: {value};")

    for name, value in sorted((theme.get("fontFamily") or {}).items()):
        lines.append(f"  --font-{name}: {_font_value(value)};")

    for name, value in sorted((theme.get("fontSize") or {}).items()):
        if isinstance(value, list):
            size, options = value[0], (value[1] if len(value) > 1 else {})
        else:
            size, options = value, {}
        lines.append(f"  --text-{name}: {size};")
        for option_key, suffix in FONT_SIZE_OPTION_SUFFIXES.items():
            if option_key in options:
                lines.append(f"  --text-{name}{suffix}: {options[option_key]};")

    return lines


def generated_block(theme: dict, material: bool) -> str:
    parts = [MARKER_START, "@theme {"]
    parts.extend(theme_lines(theme))
    parts.append("}")
    if material:
        parts.append("")
        parts.append(MATERIAL_SYMBOLS_CSS)
    parts.append(MARKER_END)
    return "\n".join(parts)


def port(source: str, css_path: str) -> None:
    theme, material = load_config(source)
    if not theme:
        raise SystemExit(f"error: no tailwind.config theme tokens found in {source}")
    block = generated_block(theme, material)

    css = ""
    if os.path.exists(css_path):
        with open(css_path) as f:
            css = f.read()

    if MARKER_START in css and MARKER_END in css:
        start = css.index(MARKER_START)
        end = css.index(MARKER_END) + len(MARKER_END)
        css = css[:start] + block + css[end:]
    else:
        import_match = re.search(r'^@import\s+["\']tailwindcss["\'];?\s*$', css, re.MULTILINE)
        if import_match:
            insert_at = import_match.end()
            css = css[:insert_at] + "\n\n" + block + css[insert_at:]
        else:
            css = (css.rstrip() + "\n\n" if css.strip() else "") + block + "\n"

    with open(css_path, "w") as f:
        f.write(css)
    token_count = len(theme_lines(theme))
    print(f"✓ Ported {token_count} design tokens from {source} into {css_path}"
          + (" (incl. Material Symbols CSS)" if material else ""))


def check(source: str, css_path: str) -> int:
    theme, material = load_config(source)
    if not os.path.exists(css_path):
        print(f"✗ {css_path} does not exist")
        return 1
    with open(css_path) as f:
        css = f.read()

    expected = [line.strip().split(":")[0] for line in theme_lines(theme)]
    missing = [var for var in expected if var not in css]
    if material and ".material-symbols-outlined" not in css:
        missing.append(".material-symbols-outlined (icon font CSS)")

    if missing:
        print(f"✗ {len(missing)} design token(s) from {source} missing in {css_path}:")
        for var in missing:
            print(f"  - {var}")
        print(f"\nRun: python3 .scripts/utils/design_tokens.py port {source} --css {css_path}")
        return 1
    print(f"✓ All {len(expected)} design tokens present in {css_path}")
    return 0


def validate(source: str) -> int:
    theme, material = load_config(source)
    tokens = theme_lines(theme)
    if not tokens:
        print(f"✗ No design tokens extractable from {source} — the export(s) carry no tailwind.config theme")
        return 1
    print(f"✓ {len(tokens)} design token(s) extractable from {source}"
          + (" (incl. Material Symbols icon font)" if material else ""))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("mode", choices=["validate", "port", "check"])
    parser.add_argument("source", help="A Stitch code.html file or a directory of screen exports (e.g. UI_design/)")
    parser.add_argument("--css", help="The app's global stylesheet containing @theme (e.g. src/app/globals.css); required for port/check")
    args = parser.parse_args()

    if args.mode == "validate":
        return validate(args.source)
    if not args.css:
        parser.error(f"--css is required for {args.mode}")
    if args.mode == "port":
        port(args.source, args.css)
        return 0
    return check(args.source, args.css)


if __name__ == "__main__":
    sys.exit(main())
